[[object]] # left wall
variant = "Quad"
q = [555.0, 0.0, 0.0]
u = [0.0, 555.0, 0.0]
v = [0.0, 0.0, 555.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.12, 0.45, 0.15]

[[object]] # right wall
variant = "Quad"
q = [0.0, 0.0, 0.0]
u = [0.0, 555.0, 0.0]
v = [0.0, 0.0, 555.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.65, 0.05, 0.05]

[[object]] # light
variant = "Quad"
q = [113.0, 554.0, 127.0]
u = [330.0, 0.0, 0.0]
v = [0.0, 0.0, 305.0]

[object.material]
variant = "DiffuseLight"

[object.material.texture]
variant = "SolidColor"
color = [7.0, 7.0, 7.0]

[[object]] # floor
variant = "Quad"
q = [0.0, 0.0, 0.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 0.0, 555.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.73, 0.73, 0.73] # white

[[object]] # ceiling
variant = "Quad"
q = [0.0, 555.0, 0.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 0.0, 555.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.73, 0.73, 0.73]

[[object]] # back wall
variant = "Quad"
q = [0.0, 0.0, 555.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 555.0, 0.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.73, 0.73, 0.73]

[[object]] # short block
variant = "ConstantMedium"
density = 0.01

[object.boundary]
variant = "Cuboid"
a = [0.0, 0.0, 0.0]
b = [165.0, 165.0, 165.0]
rotation = [0.0, -18.0, 0.0]
translation = [130.0, 0.0, 65.0]

[object.boundary.material]
variant = "Lambertian"

[object.boundary.material.texture]
variant = "SolidColor"
color = [0.73, 0.73, 0.73]

[object.material]
variant = "Isotropic"

[object.material.texture]
variant = "SolidColor"
color = [1.0, 1.0, 1.0]

[[object]] # tall block
variant = "ConstantMedium"
density = 0.01

[object.boundary]
variant = "Cuboid"
a = [0.0, 0.0, 0.0]
b = [165.0, 330.0, 165.0]
rotation = [0.0, 15.0, 0.0]
translation = [265.0, 0.0, 295.0]

[object.boundary.material]
variant = "Lambertian"

[object.boundary.material.texture]
variant = "SolidColor"
color = [0.73, 0.73, 0.73]

[object.material]
variant = "Isotropic"

[object.material.texture]
variant = "SolidColor"
color = [0.0, 0.0, 0.0]

[camera]
aspect_ratio = 1.0
image_width = 600
samples_per_pixel = 250
max_depth = 50
vertical_fov = 40.0
look_from = [278.0, 278.0, -800.0]
look_at = [278.0, 278.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0.0
focus_distance = 10.0
background = [0.0, 0.0, 0.0]
