[[entity]] # left wall
variant = "Quad"
q = [555.0, 0.0, 0.0]
u = [0.0, 555.0, 0.0]
v = [0.0, 0.0, 555.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.12, 0.45, 0.15]

[[entity]] # right wall
variant = "Quad"
q = [0.0, 0.0, 0.0]
u = [0.0, 555.0, 0.0]
v = [0.0, 0.0, 555.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.65, 0.05, 0.05]

[[entity]] # light
variant = "Quad"
q = [113.0, 554.0, 127.0]
u = [330.0, 0.0, 0.0]
v = [0.0, 0.0, 305.0]
material.variant = "DiffuseLight"
material.texture.variant = "SolidColor"
material.texture.color = [7.0, 7.0, 7.0]

[[entity]] # floor
variant = "Quad"
q = [0.0, 0.0, 0.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 0.0, 555.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.73, 0.73, 0.73] # white

[[entity]] # ceiling
variant = "Quad"
q = [0.0, 555.0, 0.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 0.0, 555.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.73, 0.73, 0.73]

[[entity]] # back wall
variant = "Quad"
q = [0.0, 0.0, 555.0]
u = [555.0, 0.0, 0.0]
v = [0.0, 555.0, 0.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.73, 0.73, 0.73]

[[entity]] # short block
variant = "ConstantMedium"
density = 0.01
material.variant = "Isotropic"
material.texture.variant = "SolidColor"
material.texture.color = [1.0, 1.0, 1.0]

[entity.boundary]
variant = "Cuboid"
a = [0.0, 0.0, 0.0]
b = [165.0, 165.0, 165.0]
rotation = [0.0, -18.0, 0.0]
translation = [130.0, 0.0, 65.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.73, 0.73, 0.73]

[[entity]] # tall block
variant = "ConstantMedium"
density = 0.01
material.variant = "Isotropic"
material.texture.variant = "SolidColor"
material.texture.color = [0.0, 0.0, 0.0]

[entity.boundary]
variant = "Cuboid"
a = [0.0, 0.0, 0.0]
b = [165.0, 330.0, 165.0]
rotation = [0.0, 15.0, 0.0]
translation = [265.0, 0.0, 295.0]
material.variant = "Lambertian"
material.texture.variant = "SolidColor"
material.texture.color = [0.73, 0.73, 0.73]

[camera]
aspect_ratio = 1.0
image_width = 400
samples_per_pixel = 500
max_depth = 50
vertical_fov = 40.0
look_from = [278.0, 278.0, -800.0]
look_at = [278.0, 278.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0.0
focus_distance = 10.0
background = [0.0, 0.0, 0.0]
