[[object]]
variant = "Sphere"
center = [0.0, 0.0, 0.0]
radius = 2.0
rotation = [50.0, -100.0, 23.5]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "Image"
image_path = "./assets/earthmap.jpg"

[camera]
aspect_ratio = 1.7777778
image_width = 800
samples_per_pixel = 100
max_depth = 50
vertical_fov = 20.0
look_from = [0.0, 0.0, 12.0]
look_at = [0.0, 0.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0
focus_distance = 10.0
background = [0.7, 0.8, 1.0]
