[[object]]
variant = "Quad"
q = [-3.0, -2.0, 5.0]
u = [0.0, 0.0, -4.0]
v = [0.0, 4.0, 0.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [1.0, 0.2, 0.2]

[[object]]
variant = "Quad"
q = [-2.0, -2.0, 0.0]
u = [4.0, 0.0, 0.0]
v = [0.0, 4.0, 0.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.2, 1, 0.2]

[[object]]
variant = "Quad"
q = [3.0, -2.0, 1.0]
u = [0.0, 0.0, 4.0]
v = [0.0, 4.0, 0.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.2, 0.2, 1.0]

[[object]]
variant = "Quad"
q = [-2.0, 3.0, 1.0]
u = [4.0, 0.0, 0.0]
v = [0.0, 0.0, 4.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [1.0, 0.5, 0.0]

[[object]]
variant = "Quad"
q = [-2.0, -3.0, 5.0]
u = [4.0, 0.0, 0.0]
v = [0.0, 0.0, -4.0]

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "SolidColor"
color = [0.2, 0.8, 0.8]

[camera]
aspect_ratio = 1.0
image_width = 800
samples_per_pixel = 100
max_depth = 50
vertical_fov = 80.0
look_from = [0.0, 0.0, 9.0]
look_at = [0.0, 0.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0.0
focus_distance = 10.0
background = [0.7, 0.8, 1.0]
