[[object]]
variant = "Sphere"
center = [0.0, -10.0, 0.0]
radius = 10.0

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "Checker"
scale = 0.32

[object.material.texture.odd]
variant = "SolidColor"
color = [0.2, 0.3, 0.1]

[object.material.texture.even]
variant = "SolidColor"
color = [0.9, 0.9, 0.9]

[[object]]
variant = "Sphere"
center = [0.0, 10.0, 0.0]
radius = 10.0

[object.material]
variant = "Lambertian"

[object.material.texture]
variant = "Checker"
scale = 0.32

[object.material.texture.odd]
variant = "SolidColor"
color = [0.2, 0.3, 0.1]

[object.material.texture.even]
variant = "SolidColor"
color = [0.9, 0.9, 0.9]

[camera]
aspect_ratio = 1.7777778
image_width = 800
samples_per_pixel = 100
max_depth = 50
vertical_fov = 20.0
look_from = [13.0, 2.0, 3.0]
look_at = [0.0, 0.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0.6
focus_distance = 10.0
background = [0.7, 0.8, 1.0]
