[[object]]
variant = "sphere"
center = [0.0, -10.0, 0.0]
radius = 10.0
material = { variant = "lambertian", texture = { variant = "checker", scale = 0.32, color1 = [
    0.2,
    0.3,
    0.1,
], color2 = [
    0.9,
    0.9,
    0.9,
] } }

[[object]]
variant = "sphere"
center = [0.0, 10.0, 0.0]
radius = 10.0
material = { variant = "lambertian", texture = { variant = "checker", scale = 0.32, color1 = [
    0.2,
    0.3,
    0.1,
], color2 = [
    0.9,
    0.9,
    0.9,
] } }

[camera]
aspect_ratio = 1.7777778
image_width = 800
samples_per_pixel = 100
max_depth = 50
vertical_fov = 20.0
look_from = [13.0, 2.0, 3.0]
look_at = [0.0, 0.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0.6
focus_distance = 10.0
