[[entity]]
variant = "Sphere"
center = [0.0, -10.0, 0.0]
radius = 10.0
material.variant = "Lambertian"
material.texture.variant = "Checker"
material.texture.scale = 0.32
material.texture.odd.variant = "SolidColor"
material.texture.odd.color = [0.2, 0.3, 0.1]
material.texture.even.variant = "SolidColor"
material.texture.even.color = [0.9, 0.9, 0.9]

[[entity]]
variant = "Sphere"
center = [0.0, 10.0, 0.0]
radius = 10.0
material.variant = "Lambertian"
material.texture.variant = "Checker"
material.texture.scale = 0.32
material.texture.odd.variant = "SolidColor"
material.texture.odd.color = [0.2, 0.3, 0.1]
material.texture.even.variant = "SolidColor"
material.texture.even.color = [0.9, 0.9, 0.9]

[camera]
aspect_ratio = 1.7777778
image_width = 800
samples_per_pixel = 100
max_depth = 50
vertical_fov = 20.0
look_from = [13.0, 2.0, 3.0]
look_at = [0.0, 0.0, 0.0]
view_up = [0.0, 1.0, 0.0]
defocus_angle = 0.6
focus_distance = 10.0
background = [0.7, 0.8, 1.0]
