[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "2.1.1"
fastrand-contrib = "0.1.0"
rayon = "1.10.0"

[profile.release]
debug = true

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
